# general
mode=acyclic
objective=km1
seed=-1
cmaxnet=1000
vcycles=1
final-epsilon=4
refine-ip=true
balance-ip=true
patoh=/Users/danielseemaier/HyperDAG/Software/patoh
rmlgp=/Users/danielseemaier/Projects/rmlgp/exe/rMLGP_interface

# main -> preprocessing -> min hash sparsifier
p-use-sparsifier=false
p-sparsifier-min-median-he-size=28
p-sparsifier-max-hyperedge-size=1200
p-sparsifier-max-cluster-size=10
p-sparsifier-min-cluster-size=2
p-sparsifier-num-hash-func=5
p-sparsifier-combined-num-hash-func=100

# main -> preprocessing -> community detection
p-detect-communities=false
p-detect-communities-in-ip=false
p-reuse-communities=false

# main -> coarsening
# memo: c-type for first cycle in recursive_bisection.h
#c-type=acyclic_cluster_coarsening_v1
#c-type=acyclic_cluster_coarsening_v2
#c-type=external
c-type=acyclic_cluster_coarsening_v2
c-type-initial=acyclic_cluster_coarsening_v2
#c-type-initial=external
c-external=rmlgp
c-mixed-contraction=1
c-s=1
c-t=160
# main -> coarsening -> rating
c-rating-score=heavy_edge
c-rating-use-communities=true
c-rating-heavy_node_penalty=no_penalty
c-rating-acceptance-criterion=best_prefer_unmatched
c-fixed-vertex-acceptance-criterion=fixed_vertex_allowed

# main -> initial partitioning
i-mode=direct
i-technique=flat
i-level=finest
#i-level=coarsest

# initial partitioning -> coarsening
i-c-type=do_nothing
#i-c-external=rmlgp

# initial partitioning -> initial partitioning
#i-algo=topological_ordering
i-algo=partitioner
i-partitioner=kahypar
#i-partitioner=rmlgp
#i-partitioner=patoh
i-balance-partition=true
i-r-type=acyclic_kway_fm_km1
#i-r-type=do_nothing
i-r-type-second=acyclic_kway_fm_km1
#i-r-type-second=do_nothing
i-r-runs=1
#i-r-runs=0
i-runs=1

# main -> local search
#r-type=acyclic_twoway_km1
r-type=acyclic_km1
#r-type=do_nothing
#r-type-second=acyclic_twoway_km1
r-type-second=acyclic_km1
r-runs=-1
r-fm-stop=adaptive_opt
r-fm-stop-alpha=1
r-fm-stop-i=350
r-soft-rebalance=false
r-hard-rebalance=false
r-refine-rebalance-moves=true
r-only-am=false
r-repeated-insert=false
r-cycle-detector=dfs

#evolutionary
partition-evolutionary=true
use-imbalanced-population=false
use-cross-combine=false
lower-epsilon-prime-bound=0.5
upper-epsilon-prime-bound=2.0
population-size=10
force-population-size=false
dynamic-population-size=true
dynamic-population-time=0.15
replace-strategy=strong-diverse
diversify-interval=1
mutation_chance=0.25

#evolutionary -> combination
combine-strategy=basic
random-combine=false
edge-frequency-chance=0.5
edge-frequency-amount=3
gamma=0.5
unlimited-coarsening=false

#evolutionary -> mutation
mutate-strategy=new-initial-partitioning-vcycle
mutate-chance=0.5
random-vcycles=true


# should be quiet?
quiet=1